name: PR Check

on:
  pull_request:
    branches: [main, 'release/*']

jobs:
  check:
    uses: calavia-org/workflows-lib/.github/workflows/pr-check-github-action.yml@v0
    with:
      validate-structure: true
      run-lint: true
      run-test: true
