name: PR Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    uses: calavia-org/workflows-lib/.github/workflows/pr-check-github-action@v0
    with:
      validate-structure: true
      run-lint: true
      run-test: false
