name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    uses: calavia-org/workflows-lib/.github/workflows/release-github-action@v0
    with:
      default-bump: patch
      release-branches: main
      validate-action: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
